# Generated by Django 4.0.2 on 2022-02-13 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 12, 34, 56, 944447, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
